### ISSUE TITLE
Breakfast Update 1

### ISSUE THREAD

**Issue by mannysmith11** [IntroToCode/RecipesCodemates9#1]
## 💬 Discussion topic

Breakfast Update

## ❗ Potential issues

There were no breakfast items 

## 👥 People to consult

@fedepacheco @OxfordOutlander 

## 📃 Details

Updated the first two parts of the Breakfast.readme (Recipe title, and servings)

**Comment by fedepacheco** [comment]
Breakfast is the most important meal of the day! I agree we should have something. Were you working on eggs, @mannysmith11?

**Comment by mannysmith11** [comment]
I think we can certainly include eggs since it is a great protein source, but we need some sort of complex carbohydrate as well to start the day. I was thinking we could include grits @fedepacheco @OxfordOutlander

**Comment by ecskimball** [comment]
Grits or oatmeal would be a great addition as carb.
