### ISSUE TITLE
Problem with dinner 

### ISSUE THREAD

**Issue by OxfordOutlander** [IntroToCode/RecipesCodemates9#3]
## 💬 Discussion topic

Dinner

## ❗ Potential issues

There are no recipes! 

## 👥 People to consult

Manny, Fede. 

## 📃 Details

Text

**Comment by fedepacheco** [comment]
I just added a burger as a potential dinner option. Would that work?

**Comment by fedepacheco** [comment]
@ecskimball any thoughts before we close this one?

**Comment by mannysmith11** [comment]
@OxfordOutlander @dcerda9  put together the dinner recipe and I will double check for completion. Please comment any feedback you have on his input. Thanks! 🥇
