### ISSUE TITLE
Going vegan?

### ISSUE THREAD

**Issue by fedepacheco** [IntroToCode/RecipesCodemates9#5]
## 💬 Discussion topic

Should we go vegan?

## ❗ Potential issues

It implies changing the ingredients but it is trendy

## 👥 People to consult

@mannysmith11 @OxfordOutlander 

## 📃 Details

No further details

**Comment by OxfordOutlander** [comment]
not a smart move

**Comment by fedepacheco** [comment]
Could you elaborate please? @OxfordOutlander[ It's a big trend in consumers ](https://www.buzzworthy.com/whats-driving-the-vegan-trend/)

**Comment by OxfordOutlander** [comment]
Ok im convined.
