### ISSUE TITLE
How do we make a cheese sandwich more exciting?

### ISSUE THREAD

**Issue by ecskimball** [IntroToCode/RecipesCodemates9#9]
## 💬 Discussion topic

I'm concerned a normal cheese sandwich is boring. 

## ❗ Potential issues

If the lunch is boring, will people buy our cookbook? 

## 👥 People to consult

@fedepacheco 

## 📃 Details

Perhaps we can make it a grilled cheese. People love things that are grilled.

**Comment by fedepacheco** [comment]
That sounds like an interesting addition. I found a [good source](https://www.google.com/search?q=grilled+cheese+sandwich+trend&rlz=1C5CHFA_enCR729CR729&oq=grilled+cheese+sandwich+trend&aqs=chrome..69i57j0i457j0j0i22i30l4j69i61.4443j0j7&sourceid=chrome&ie=UTF-8). Great idea Ellen. 😸

**Comment by mannysmith11** [comment]
Thanks @fedepacheco and @ecskimball  I also found a resource that we can use to embellish on the cheese sandwich. Please see the resource [HERE](https://www.allrecipes.com/recipe/23891/grilled-cheese-sandwich/).
